apiVersion: apps/v1
kind: Deployment
metadata:
  name: retailshopingcart-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: your-app
  template:
    metadata:
      labels:
        app: your-app
    spec:
      containers:
      - name: retailshoppingcart-container
        image: aniketh8341/casestudyretailshoppingcart:latest
        ports:
          - containerPort: 3000
        env:
         - name: MONGODB_URI
           value: "mongodb://mongo:27017/shopping-cart"
      - name: mongo
        image: mongo:latest
        ports:
           - containerPort: 27017